name: Formatting

on:
  push:
    branches:
      - 'master'
      - 'staging**'
  pull_request:
    branches:
      '**'
  merge_group:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # formatting and basic install on cpu-only machine
  formatting:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: environment
        run: |
          which python
          python --version

      - name: Install deepspeed
        run: |
          pip install .[dev,autotuning,triton]
          ds_report

      - name: Formatting checks
        run: |
           pip show pre-commit clang-format
           pre-commit run --all-files
