name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      'staging**'
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # unit tests running on nvidia gpus
  unit-tests:
    runs-on: [self-hosted, nvidia]

    steps:
      - uses: actions/checkout@v2

      - name: environment
        run: |
          nvidia-smi
          echo $GITHUB_WORKSPACE
          pwd

      - name: Install deepspeed
        run: |
          pip install .[dev]
          ds_report

      - name: Unit tests
        run: |
          if [[ -d ./torch-extensions ]]; then rm -rf ./torch-extensions; fi
          TORCH_EXTENSIONS_DIR=./torch-extensions pytest --durations=0 --forked --verbose -x tests/unit/
