name: nv-accelerate-v100

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'blogs/**'
      - 'deepspeed/inference/v2/**'
      - 'tests/unit/inference/v2/**'
  merge_group:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: [self-hosted, nvidia, cu117, v100]

    steps:
      - uses: actions/checkout@v4

      - name: environment
        run: |
          pip install -U --cache-dir $TORCH_CACHE torch torchvision --index-url https://download.pytorch.org/whl/cu118
          python -c "import torch; print('torch:', torch.__version__, torch)"
          python -c "import torch; print('CUDA available:', torch.cuda.is_available())"

      - name: Python environment
        run: |
          pip list

      - name: Install deepspeed
        run: |
          pip uninstall --yes deepspeed
          pip install .[dev,autotuning]
          ds_report

      - name: HF Accelerate tests
        run: |
          if [[ -d ./torch-extensions ]]; then rm -rf ./torch-extensions; fi
          git clone https://github.com/huggingface/accelerate
          cd accelerate
          # tmp fix
          git checkout 5f4ba04628eeea14f9d248ab0e54399899503532
          git rev-parse --short HEAD
          # installing dependencies
          pip install .[testing]
          # force protobuf version due to issues
          pip install "protobuf<4.21.0"
          # tmp fix: force newer datasets version
          #pip install "datasets>=2.0.0"
          pip list
          TORCH_EXTENSIONS_DIR=./torch-extensions pytest --color=yes --durations=0 --verbose tests/deepspeed
