name: nv-nightly

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/nv-nightly.yml'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
    contents: read
    issues: write

jobs:
  unit-tests:
    runs-on: [self-hosted, nvidia, cu124, v100]

    steps:
      - uses: actions/checkout@v4

      - id: setup-venv
        uses: ./.github/workflows/setup-venv

      - name: Install pytorch
        run: |
          pip install -U --cache-dir $TORCH_CACHE torch torchvision --index-url https://download.pytorch.org/whl/cu124
          python -c "import torch; print('torch:', torch.__version__, torch)"
          python -c "import torch; print('CUDA available:', torch.cuda.is_available())"

      - name: Install transformers
        run: |
          git clone https://github.com/huggingface/transformers
          cd transformers
          # if needed switch to the last known good SHA until transformers@master is fixed
          git checkout v4.42.4
          git rev-parse --short HEAD
          pip install .

      - name: Install datasets
        run: |
          pip install datasets

      - name: Install deepspeed
        run: |
          pip install .[dev,1bit,autotuning,inf]
          ds_report

      - name: Install lm-eval
        run: |
          pip uninstall --yes lm-eval
          pip install git+https://github.com/EleutherAI/lm-evaluation-harness
          # This is required until lm-eval makes a new release. v0.2.0 is
          # broken for latest version of transformers

      - name: Python environment
        run: |
          pip list

      - name: Unit tests
        run: |
          unset TORCH_CUDA_ARCH_LIST # only jit compile for current arch
          cd tests
          TRANSFORMERS_CACHE=/blob/transformers_cache/ TORCH_EXTENSIONS_DIR=./torch-extensions pytest --color=yes --durations=0 --forked --verbose -m 'nightly' unit/ --torch_ver="1.13" --cuda_ver="11.6"
